#!/bin/bash
git clone https://github.com/OCA/account-analytic.git -b 16.0
git clone https://github.com/OCA/account-budgeting.git -b 16.0
git clone https://github.com/OCA/account-consolidation.git -b 16.0
git clone https://github.com/OCA/account-financial-reporting.git -b 16.0
git clone https://github.com/OCA/account-financial-tools.git -b 16.0
git clone https://github.com/OCA/account-fiscal-rule.git -b 16.0
git clone https://github.com/OCA/account-invoice-reporting.git -b 16.0
git clone https://github.com/OCA/account-invoicing.git -b 16.0
git clone https://github.com/OCA/account-payment.git -b 16.0
git clone https://github.com/OCA/account-reconcile.git -b 16.0
git clone https://github.com/OCA/agreement.git -b 16.0
git clone https://github.com/OCA/ansible-odoo.git -b 16.0
git clone https://github.com/OCA/apps-store.git -b 16.0
git clone https://github.com/OCA/bank-payment.git -b 16.0
git clone https://github.com/OCA/bank-statement-import.git -b 16.0
git clone https://github.com/OCA/brand.git -b 16.0
git clone https://github.com/OCA/business-requirement.git -b 16.0
git clone https://github.com/OCA/calendar.git -b 16.0
git clone https://github.com/OCA/commission.git -b 16.0
git clone https://github.com/OCA/community-data-files.git -b 16.0
git clone https://github.com/OCA/connector.git -b 16.0
git clone https://github.com/OCA/connector-accountedge.git -b 16.0
git clone https://github.com/OCA/connector-cmis.git -b 16.0
git clone https://github.com/OCA/connector-ecommerce.git -b 16.0
git clone https://github.com/OCA/connector-infor.git -b 16.0
git clone https://github.com/OCA/connector-interfaces.git -b 16.0
git clone https://github.com/OCA/connector-jira.git -b 16.0
git clone https://github.com/OCA/connector-lengow.git -b 16.0
git clone https://github.com/OCA/connector-lims.git -b 16.0
git clone https://github.com/OCA/connector-magento.git -b 16.0
git clone https://github.com/OCA/connector-magento-php-extension.git -b 16.0
git clone https://github.com/OCA/connector-odoo2odoo.git -b 16.0
git clone https://github.com/OCA/connector-prestashop.git -b 16.0
git clone https://github.com/OCA/connector-redmine.git -b 16.0
git clone https://github.com/OCA/connector-sage.git -b 16.0
git clone https://github.com/OCA/connector-salesforce.git -b 16.0
git clone https://github.com/OCA/connector-spscommerce.git -b 16.0
git clone https://github.com/OCA/connector-telephony.git -b 16.0
git clone https://github.com/OCA/connector-woocommerce.git -b 16.0
git clone https://github.com/OCA/contract.git -b 16.0
git clone https://github.com/OCA/contribute-md-template.git -b 16.0
git clone https://github.com/OCA/cooperative.git -b 16.0
git clone https://github.com/OCA/credit-control.git -b 16.0
git clone https://github.com/OCA/crm.git -b 16.0
git clone https://github.com/OCA/currency.git -b 16.0
git clone https://github.com/OCA/data-protection.git -b 16.0
git clone https://github.com/OCA/ddmrp.git -b 16.0
git clone https://github.com/OCA/delivery-carrier.git -b 16.0
git clone https://github.com/OCA/department.git -b 16.0
git clone https://github.com/OCA/dms.git -b 16.0
git clone https://github.com/OCA/donation.git -b 16.0
git clone https://github.com/OCA/dotnet.git -b 16.0
git clone https://github.com/OCA/e-commerce.git -b 16.0
git clone https://github.com/OCA/edi.git -b 16.0
git clone https://github.com/OCA/event.git -b 16.0
git clone https://github.com/OCA/field-service.git -b 16.0
git clone https://github.com/OCA/fleet.git -b 16.0
git clone https://github.com/OCA/geospatial.git -b 16.0
git clone https://github.com/OCA/helpdesk.git -b 16.0
git clone https://github.com/OCA/hr.git -b 16.0
git clone https://github.com/OCA/hr-attendance.git -b 16.0
git clone https://github.com/OCA/hr-expense.git -b 16.0
git clone https://github.com/OCA/hr-holidays.git -b 16.0
git clone https://github.com/OCA/infrastructure.git -b 16.0
git clone https://github.com/OCA/interface-github.git -b 16.0
git clone https://github.com/OCA/intrastat-extrastat.git -b 16.0
git clone https://github.com/OCA/iot.git -b 16.0
git clone https://github.com/OCA/knowledge.git -b 16.0
git clone https://github.com/OCA/l10n-argentina.git -b 16.0
git clone https://github.com/OCA/l10n-austria.git -b 16.0
git clone https://github.com/OCA/l10n-belarus.git -b 16.0
git clone https://github.com/OCA/l10n-belgium.git -b 16.0
git clone https://github.com/OCA/l10n-brazil.git -b 16.0
git clone https://github.com/OCA/l10n-cambodia.git -b 16.0
git clone https://github.com/OCA/l10n-canada.git -b 16.0
git clone https://github.com/OCA/l10n-chile.git -b 16.0
git clone https://github.com/OCA/l10n-china.git -b 16.0
git clone https://github.com/OCA/l10n-colombia.git -b 16.0
git clone https://github.com/OCA/l10n-costa-rica.git -b 16.0
git clone https://github.com/OCA/l10n-croatia.git -b 16.0
git clone https://github.com/OCA/l10n-ecuador.git -b 16.0
git clone https://github.com/OCA/l10n-estonia.git -b 16.0
git clone https://github.com/OCA/l10n-ethiopia.git -b 16.0
git clone https://github.com/OCA/l10n-finland.git -b 16.0
git clone https://github.com/OCA/l10n-france.git -b 16.0
git clone https://github.com/OCA/l10n-germany.git -b 16.0
git clone https://github.com/OCA/l10n-greece.git -b 16.0
git clone https://github.com/OCA/l10n-india.git -b 16.0
git clone https://github.com/OCA/l10n-indonesia.git -b 16.0
git clone https://github.com/OCA/l10n-iran.git -b 16.0
git clone https://github.com/OCA/l10n-ireland.git -b 16.0
git clone https://github.com/OCA/l10n-italy.git -b 16.0
git clone https://github.com/OCA/l10n-japan.git -b 16.0
git clone https://github.com/OCA/l10n-luxemburg.git -b 16.0
git clone https://github.com/OCA/l10n-macedonia.git -b 16.0
git clone https://github.com/OCA/l10n-mexico.git -b 16.0
git clone https://github.com/OCA/l10n-morocco.git -b 16.0
git clone https://github.com/OCA/l10n-netherlands.git -b 16.0
git clone https://github.com/OCA/l10n-norway.git -b 16.0
git clone https://github.com/OCA/l10n-peru.git -b 16.0
git clone https://github.com/OCA/l10n-poland.git -b 16.0
git clone https://github.com/OCA/l10n-portugal.git -b 16.0
git clone https://github.com/OCA/l10n-romania.git -b 16.0
git clone https://github.com/OCA/l10n-russia.git -b 16.0
git clone https://github.com/OCA/l10n-slovenia.git -b 16.0
git clone https://github.com/OCA/l10n-spain.git -b 16.0
git clone https://github.com/OCA/l10n-switzerland.git -b 16.0
git clone https://github.com/OCA/l10n-taiwan.git -b 16.0
git clone https://github.com/OCA/l10n-thailand.git -b 16.0
git clone https://github.com/OCA/l10n-turkey.git -b 16.0
git clone https://github.com/OCA/l10n-ukraine.git -b 16.0
git clone https://github.com/OCA/l10n-united-kingdom.git -b 16.0
git clone https://github.com/OCA/l10n-uruguay.git -b 16.0
git clone https://github.com/OCA/l10n-usa.git -b 16.0
git clone https://github.com/OCA/l10n-venezuela.git -b 16.0
git clone https://github.com/OCA/l10n-vietnam.git -b 16.0
git clone https://github.com/OCA/maintainer-quality-tools.git -b 16.0
git clone https://github.com/OCA/maintainer-tools.git -b 16.0
git clone https://github.com/OCA/maintenance.git -b 16.0
git clone https://github.com/OCA/management-system.git -b 16.0
git clone https://github.com/OCA/manufacture.git -b 16.0
git clone https://github.com/OCA/manufacture-reporting.git -b 16.0
git clone https://github.com/OCA/margin-analysis.git -b 16.0
git clone https://github.com/OCA/mirrors-flake8.git -b 16.0
git clone https://github.com/OCA/mis-builder.git -b 16.0
git clone https://github.com/OCA/mis-builder-contrib.git -b 16.0
git clone https://github.com/OCA/multi-company.git -b 16.0
git clone https://github.com/OCA/odoo-pim.git -b 16.0
git clone https://github.com/OCA/odoo-sentinel.git -b 16.0
git clone https://github.com/OCA/odoo-sphinx-autodoc.git -b 16.0
git clone https://github.com/OCA/odoorpc.git -b 16.0
git clone https://github.com/OCA/operating-unit.git -b 16.0
git clone https://github.com/OCA/partner-contact.git -b 16.0
git clone https://github.com/OCA/payroll.git -b 16.0
git clone https://github.com/OCA/pms.git -b 16.0
git clone https://github.com/OCA/pos.git -b 16.0
git clone https://github.com/OCA/product-attribute.git -b 16.0
git clone https://github.com/OCA/product-configurator.git -b 16.0
git clone https://github.com/OCA/product-kitting.git -b 16.0
git clone https://github.com/OCA/product-pack.git -b 16.0
git clone https://github.com/OCA/product-variant.git -b 16.0
git clone https://github.com/OCA/program.git -b 16.0
git clone https://github.com/OCA/project.git -b 16.0
git clone https://github.com/OCA/project-agile.git -b 16.0
git clone https://github.com/OCA/project-reporting.git -b 16.0
git clone https://github.com/OCA/purchase-reporting.git -b 16.0
git clone https://github.com/OCA/purchase-workflow.git -b 16.0
git clone https://github.com/OCA/pwa-builder.git -b 16.0
git clone https://github.com/OCA/pylint-odoo.git -b 16.0
git clone https://github.com/OCA/queue.git -b 16.0
git clone https://github.com/OCA/repair.git -b 16.0
git clone https://github.com/OCA/report-print-send.git -b 16.0
git clone https://github.com/OCA/reporting-engine.git -b 16.0
git clone https://github.com/OCA/rest-api.git -b 16.0
git clone https://github.com/OCA/rest-framework.git -b 16.0
git clone https://github.com/OCA/rma.git -b 16.0
git clone https://github.com/OCA/role-policy.git -b 16.0
git clone https://github.com/OCA/runbot-addons.git -b 16.0
git clone https://github.com/OCA/sale-financial.git -b 16.0
git clone https://github.com/OCA/sale-promotion.git -b 16.0
git clone https://github.com/OCA/sale-reporting.git -b 16.0
git clone https://github.com/OCA/sale-workflow.git -b 16.0
git clone https://github.com/OCA/search-engine.git -b 16.0
git clone https://github.com/OCA/server-auth.git -b 16.0
git clone https://github.com/OCA/server-backend.git -b 16.0
git clone https://github.com/OCA/server-brand.git -b 16.0
git clone https://github.com/OCA/server-env.git -b 16.0
git clone https://github.com/OCA/server-tools.git -b 16.0
git clone https://github.com/OCA/server-ux.git -b 16.0
git clone https://github.com/OCA/shift-planning.git -b 16.0
git clone https://github.com/OCA/social.git -b 16.0
git clone https://github.com/OCA/stock-logistics-availability.git -b 16.0
git clone https://github.com/OCA/stock-logistics-barcode.git -b 16.0
git clone https://github.com/OCA/stock-logistics-interfaces.git -b 16.0
git clone https://github.com/OCA/stock-logistics-orderpoint.git -b 16.0
git clone https://github.com/OCA/stock-logistics-reporting.git -b 16.0
git clone https://github.com/OCA/stock-logistics-request.git -b 16.0
git clone https://github.com/OCA/stock-logistics-tracking.git -b 16.0
git clone https://github.com/OCA/stock-logistics-transport.git -b 16.0
git clone https://github.com/OCA/stock-logistics-warehouse.git -b 16.0
git clone https://github.com/OCA/stock-logistics-workflow.git -b 16.0
git clone https://github.com/OCA/storage.git -b 16.0
git clone https://github.com/OCA/survey.git -b 16.0
git clone https://github.com/OCA/timesheet.git -b 16.0
git clone https://github.com/OCA/vertical-abbey.git -b 16.0
git clone https://github.com/OCA/vertical-agriculture.git -b 16.0
git clone https://github.com/OCA/vertical-association.git -b 16.0
git clone https://github.com/OCA/vertical-community.git -b 16.0
git clone https://github.com/OCA/vertical-construction.git -b 16.0
git clone https://github.com/OCA/vertical-cooperative-supermarket.git -b 16.0
git clone https://github.com/OCA/vertical-edition.git -b 16.0
git clone https://github.com/OCA/vertical-education.git -b 16.0
git clone https://github.com/OCA/vertical-hotel.git -b 16.0
git clone https://github.com/OCA/vertical-isp.git -b 16.0
git clone https://github.com/OCA/vertical-medical.git -b 16.0
git clone https://github.com/OCA/vertical-ngo.git -b 16.0
git clone https://github.com/OCA/vertical-realestate.git -b 16.0
git clone https://github.com/OCA/vertical-rental.git -b 16.0
git clone https://github.com/OCA/vertical-travel.git -b 16.0
git clone https://github.com/OCA/wallet.git -b 16.0
git clone https://github.com/OCA/web.git -b 16.0
git clone https://github.com/OCA/web-api.git -b 16.0
git clone https://github.com/OCA/webhook.git -b 16.0
git clone https://github.com/OCA/webkit-tools.git -b 16.0
git clone https://github.com/OCA/website.git -b 16.0
git clone https://github.com/OCA/website-cms.git -b 16.0
git clone https://github.com/OCA/website-themes.git -b 16.0
git clone https://github.com/OCA/wms.git -b 16.0
