#!/bin/bash
git -C account-analytic pull
git -C account-budgeting pull
git -C account-consolidation pull
git -C account-financial-reporting pull
git -C account-financial-tools pull
git -C account-fiscal-rule pull
git -C account-invoice-reporting pull
git -C account-invoicing pull
git -C account-payment pull
git -C account-reconcile pull
git -C agreement pull
#git -C ansible-odoo pull
git -C apps-store pull
git -C bank-payment pull
git -C bank-statement-import pull
git -C brand pull
git -C business-requirement pull
git -C calendar pull
git -C commission pull
git -C community-data-files pull
git -C connector pull
git -C connector-accountedge pull
git -C connector-cmis pull
git -C connector-ecommerce pull
git -C connector-infor pull
git -C connector-interfaces pull
git -C connector-jira pull
git -C connector-lengow pull
git -C connector-lims pull
git -C connector-magento pull
#git -C connector-magento-php-extension pull
git -C connector-odoo2odoo pull
git -C connector-prestashop pull
git -C connector-redmine pull
git -C connector-sage pull
git -C connector-salesforce pull
git -C connector-spscommerce pull
git -C connector-telephony pull
git -C connector-woocommerce pull
git -C contract pull
#git -C contribute-md-template pull
git -C cooperative pull
git -C credit-control pull
git -C crm pull
git -C currency pull
git -C data-protection pull
git -C ddmrp pull
git -C delivery-carrier pull
git -C department pull
git -C dms pull
git -C donation pull
git -C dotnet pull
git -C e-commerce pull
git -C edi pull
git -C event pull
git -C field-service pull
git -C fleet pull
git -C geospatial pull
git -C helpdesk pull
git -C hr pull
git -C hr-attendance pull
git -C hr-expense pull
git -C hr-holidays pull
git -C infrastructure pull
git -C interface-github pull
git -C intrastat-extrastat pull
git -C iot pull
git -C knowledge pull
git -C l10n-argentina pull
git -C l10n-austria pull
git -C l10n-belarus pull
git -C l10n-belgium pull
git -C l10n-brazil pull
git -C l10n-cambodia pull
git -C l10n-canada pull
git -C l10n-chile pull
git -C l10n-china pull
git -C l10n-colombia pull
git -C l10n-costa-rica pull
git -C l10n-croatia pull
git -C l10n-ecuador pull
git -C l10n-estonia pull
git -C l10n-ethiopia pull
git -C l10n-finland pull
git -C l10n-france pull
git -C l10n-germany pull
git -C l10n-greece pull
git -C l10n-india pull
git -C l10n-indonesia pull
git -C l10n-iran pull
git -C l10n-ireland pull
git -C l10n-italy pull
git -C l10n-japan pull
git -C l10n-luxemburg pull
git -C l10n-macedonia pull
git -C l10n-mexico pull
git -C l10n-morocco pull
git -C l10n-netherlands pull
git -C l10n-norway pull
git -C l10n-peru pull
git -C l10n-poland pull
git -C l10n-portugal pull
git -C l10n-romania pull
git -C l10n-russia pull
git -C l10n-slovenia pull
git -C l10n-spain pull
git -C l10n-switzerland pull
git -C l10n-taiwan pull
git -C l10n-thailand pull
git -C l10n-turkey pull
git -C l10n-ukraine pull
git -C l10n-united-kingdom pull
git -C l10n-uruguay pull
git -C l10n-usa pull
git -C l10n-venezuela pull
git -C l10n-vietnam pull
#git -C maintainer-quality-tools pull
#git -C maintainer-tools pull
git -C maintenance pull
git -C management-system pull
git -C manufacture pull
git -C manufacture-reporting pull
git -C margin-analysis pull
#git -C mirrors-flake8 pull
git -C mis-builder pull
git -C mis-builder-contrib pull
git -C multi-company pull
git -C odoo-pim pull
#git -C odoo-sentinel pull
#git -C odoo-sphinx-autodoc pull
#git -C odoorpc pull
git -C operating-unit pull
git -C partner-contact pull
git -C payroll pull
git -C pms pull
git -C pos pull
git -C product-attribute pull
git -C product-configurator pull
git -C product-kitting pull
git -C product-pack pull
git -C product-variant pull
git -C program pull
git -C project pull
git -C project-agile pull
git -C project-reporting pull
git -C purchase-reporting pull
git -C purchase-workflow pull
git -C pwa-builder pull
#git -C pylint-odoo pull
git -C queue pull
git -C repair pull
git -C report-print-send pull
git -C reporting-engine pull
git -C rest-api pull
git -C rest-framework pull
git -C rma pull
git -C role-policy pull
git -C runbot-addons pull
git -C sale-financial pull
git -C sale-promotion pull
git -C sale-reporting pull
git -C sale-workflow pull
git -C search-engine pull
git -C server-auth pull
git -C server-backend pull
git -C server-brand pull
git -C server-env pull
git -C server-tools pull
git -C server-ux pull
git -C shift-planning pull
git -C social pull
git -C stock-logistics-availability pull
git -C stock-logistics-barcode pull
git -C stock-logistics-interfaces pull
git -C stock-logistics-orderpoint pull
git -C stock-logistics-reporting pull
git -C stock-logistics-request pull
git -C stock-logistics-tracking pull
git -C stock-logistics-transport pull
git -C stock-logistics-warehouse pull
git -C stock-logistics-workflow pull
git -C storage pull
git -C survey pull
git -C timesheet pull
git -C vertical-abbey pull
git -C vertical-agriculture pull
git -C vertical-association pull
git -C vertical-community pull
git -C vertical-construction pull
git -C vertical-cooperative-supermarket pull
git -C vertical-edition pull
git -C vertical-education pull
git -C vertical-hotel pull
git -C vertical-isp pull
git -C vertical-medical pull
git -C vertical-ngo pull
git -C vertical-realestate pull
git -C vertical-rental pull
git -C vertical-travel pull
git -C wallet pull
git -C web pull
git -C web-api pull
git -C webhook pull
git -C webkit-tools pull
git -C website pull
git -C website-cms pull
git -C website-themes pull
git -C wms pull
