#!/bin/bash
git clone https://github.com/OCA/account-reconcile.git -b 15.0
git clone https://github.com/OCA/account-budgeting.git -b 15.0
git clone https://github.com/OCA/partner-contact.git -b 15.0
git clone https://github.com/OCA/crm.git -b 15.0
git clone https://github.com/OCA/e-commerce.git -b 15.0
git clone https://github.com/OCA/account-analytic.git -b 15.0
git clone https://github.com/OCA/website.git -b 15.0
git clone https://github.com/OCA/hr.git -b 15.0
git clone https://github.com/OCA/manufacture.git -b 15.0
git clone https://github.com/OCA/account-financial-reporting.git -b 15.0
git clone https://github.com/OCA/web.git -b 15.0
git clone https://github.com/OCA/sale-promotion.git -b 15.0
git clone https://github.com/OCA/l10n-germany.git -b 15.0
git clone https://github.com/OCA/wms.git -b 15.0
git clone https://github.com/OCA/website-themes.git -b 15.0
git clone https://github.com/OCA/website-cms.git -b 15.0
git clone https://github.com/OCA/vertical-travel.git -b 15.0
git clone https://github.com/OCA/vertical-rental.git -b 15.0
git clone https://github.com/OCA/vertical-realestate.git -b 15.0
git clone https://github.com/OCA/vertical-ngo.git -b 15.0
git clone https://github.com/OCA/vertical-medical.git -b 15.0
git clone https://github.com/OCA/vertical-isp.git -b 15.0
git clone https://github.com/OCA/vertical-hotel.git -b 15.0
git clone https://github.com/OCA/vertical-education.git -b 15.0
git clone https://github.com/OCA/vertical-edition.git -b 15.0
git clone https://github.com/OCA/vertical-construction.git -b 15.0
git clone https://github.com/OCA/vertical-community.git -b 15.0
git clone https://github.com/OCA/vertical-association.git -b 15.0
git clone https://github.com/OCA/vertical-agriculture.git -b 15.0
git clone https://github.com/OCA/vertical-abbey.git -b 15.0
git clone https://github.com/OCA/timesheet.git -b 15.0
git clone https://github.com/OCA/survey.git -b 15.0
git clone https://github.com/OCA/storage.git -b 15.0
git clone https://github.com/OCA/stock-logistics-workflow.git -b 15.0
git clone https://github.com/OCA/stock-logistics-warehouse.git -b 15.0
git clone https://github.com/OCA/stock-logistics-transport.git -b 15.0
git clone https://github.com/OCA/stock-logistics-tracking.git -b 15.0
git clone https://github.com/OCA/stock-logistics-reporting.git -b 15.0
git clone https://github.com/OCA/stock-logistics-barcode.git -b 15.0
git clone https://github.com/OCA/social.git -b 15.0
git clone https://github.com/OCA/server-ux.git -b 15.0
git clone https://github.com/OCA/server-tools.git -b 15.0
git clone https://github.com/OCA/server-env.git -b 15.0
git clone https://github.com/OCA/server-brand.git -b 15.0
git clone https://github.com/OCA/server-backend.git -b 15.0
git clone https://github.com/OCA/server-auth.git -b 15.0
git clone https://github.com/OCA/search-engine.git -b 15.0
git clone https://github.com/OCA/sale-workflow.git -b 15.0
git clone https://github.com/OCA/sale-reporting.git -b 15.0
git clone https://github.com/OCA/sale-financial.git -b 15.0
git clone https://github.com/OCA/rma.git -b 15.0
git clone https://github.com/OCA/reporting-engine.git -b 15.0
git clone https://github.com/OCA/report-print-send.git -b 15.0
git clone https://github.com/OCA/purchase-workflow.git -b 15.0
git clone https://github.com/OCA/purchase-reporting.git -b 15.0
git clone https://github.com/OCA/project-reporting.git -b 15.0
git clone https://github.com/OCA/project-agile.git -b 15.0
git clone https://github.com/OCA/project.git -b 15.0
git clone https://github.com/OCA/product-variant.git -b 15.0
git clone https://github.com/OCA/program.git -b 15.0
git clone https://github.com/OCA/product-pack.git -b 15.0
git clone https://github.com/OCA/product-kitting.git -b 15.0
git clone https://github.com/OCA/product-configurator.git -b 15.0
git clone https://github.com/OCA/product-attribute.git -b 15.0
git clone https://github.com/OCA/pos.git -b 15.0
git clone https://github.com/OCA/knowledge.git -b 15.0
git clone https://github.com/OCA/pms.git -b 15.0
git clone https://github.com/OCA/operating-unit.git -b 15.0
git clone https://github.com/OCA/odoo-pim.git -b 15.0
git clone https://github.com/OCA/multi-company.git -b 15.0
git clone https://github.com/OCA/mis-builder-contrib.git -b 15.0
git clone https://github.com/OCA/margin-analysis.git -b 15.0
git clone https://github.com/OCA/management-system.git -b 15.0
git clone https://github.com/OCA/maintenance.git -b 15.0
git clone https://github.com/OCA/iot.git -b 15.0
git clone https://github.com/OCA/intrastat-extrastat.git -b 15.0
git clone https://github.com/OCA/hr-holidays.git -b 15.0
git clone https://github.com/OCA/hr-expense.git -b 15.0
git clone https://github.com/OCA/hr-attendance.git -b 15.0
git clone https://github.com/OCA/helpdesk.git -b 15.0
git clone https://github.com/OCA/geospatial.git -b 15.0
git clone https://github.com/OCA/fleet.git -b 15.0
git clone https://github.com/OCA/field-service.git -b 15.0
git clone https://github.com/OCA/event.git -b 15.0
git clone https://github.com/OCA/delivery-carrier.git -b 15.0
git clone https://github.com/OCA/donation.git -b 15.0
git clone https://github.com/OCA/dms.git -b 15.0
git clone https://github.com/OCA/department.git -b 15.0
git clone https://github.com/OCA/ddmrp.git -b 15.0
git clone https://github.com/OCA/data-protection.git -b 15.0
git clone https://github.com/OCA/currency.git -b 15.0
git clone https://github.com/OCA/credit-control.git -b 15.0
git clone https://github.com/OCA/contract.git -b 15.0
git clone https://github.com/OCA/connector-woocommerce.git -b 15.0
git clone https://github.com/OCA/commission.git -b 15.0
git clone https://github.com/OCA/calendar.git -b 15.0
git clone https://github.com/OCA/business-requirement.git -b 15.0
git clone https://github.com/OCA/brand.git -b 15.0
git clone https://github.com/OCA/bank-statement-import.git -b 15.0
git clone https://github.com/OCA/bank-payment.git -b 15.0
git clone https://github.com/OCA/account-payment.git -b 15.0
git clone https://github.com/OCA/account-invoicing.git -b 15.0
git clone https://github.com/OCA/account-invoice-reporting.git -b 15.0
git clone https://github.com/OCA/account-closing.git -b 15.0
git clone https://github.com/OCA/account-fiscal-rule.git -b 15.0
git clone https://github.com/OCA/account-financial-tools.git -b 15.0
git clone https://github.com/OCA/account-consolidation.git -b 15.0
git clone https://github.com/OCA/payroll.git -b 15.0
git clone https://github.com/OCA/mis-builder.git -b 15.0
git clone https://github.com/OCA/manufacture-reporting.git -b 15.0
